{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] \ub300\uc0c1 \ucef4\ud4e8\ud130\uc5d0\uc11c \uc5f0\uacb0\uc744 \uac70\ubd80\ud588\uc73c\ubbc0\ub85c \uc5f0\uacb0\ud558\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000027441867410>: Failed to establish a new connection: [WinError 10061] \ub300\uc0c1 \ucef4\ud4e8\ud130\uc5d0\uc11c \uc5f0\uacb0\uc744 \uac70\ubd80\ud588\uc73c\ubbc0\ub85c \uc5f0\uacb0\ud558\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=55407): Max retries exceeded with url: /session/692200e52ff85dc96cf6470f860a549c/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027441867410>: Failed to establish a new connection: [WinError 10061] \ub300\uc0c1 \ucef4\ud4e8\ud130\uc5d0\uc11c \uc5f0\uacb0\uc744 \uac70\ubd80\ud588\uc73c\ubbc0\ub85c \uc5f0\uacb0\ud558\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4'))\n", "test_name": "test_ddd", "rerun": "0"}}, "suite_name": "tests/test_sibal.py"}}}, "date": "September 20, 2024", "start_time": 1726837333.5102053, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}